# Generated by Django 6.0.2 on 2026-02-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('school', models.CharField(max_length=255)),
                ('abbrv', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('short_display_name', models.CharField(max_length=255)),
                ('mascot', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_color', models.CharField(blank=True, max_length=7, null=True)),
                ('secondary_color', models.CharField(blank=True, max_length=7, null=True)),
                ('current_venue_id', models.IntegerField(blank=True, null=True)),
                ('current_venue_name', models.CharField(blank=True, max_length=200, null=True)),
                ('current_city', models.CharField(blank=True, max_length=100, null=True)),
                ('current_state', models.CharField(blank=True, max_length=50, null=True)),
                ('conference_id', models.IntegerField(blank=True, null=True)),
                ('conference', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
