# Generated by Django 6.0.2 on 2026-03-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencourt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('abbrv', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=255)),
            ],
        ),
    ]
