# Generated by Django 6.0.2 on 2026-03-06 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencourt', '0002_conference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='conference_id',
            new_name='api_conference_id',
        ),
        migrations.AlterField(
            model_name='team',
            name='conference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='opencourt.conference'),
        ),
    ]
