# Generated by Django 6.0.2 on 2026-03-10 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencourt', '0003_rename_conference_id_team_api_conference_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSeasonStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('season_label', models.CharField(max_length=20)),
                ('games', models.IntegerField(blank=True, null=True)),
                ('wins', models.FloatField(blank=True, null=True)),
                ('losses', models.FloatField(blank=True, null=True)),
                ('win_pct', models.FloatField(blank=True, null=True)),
                ('pace', models.FloatField(blank=True, null=True)),
                ('total_minutes', models.FloatField(blank=True, null=True)),
                ('off_fg_made', models.FloatField(blank=True, null=True)),
                ('off_fg_attempted', models.FloatField(blank=True, null=True)),
                ('off_fg_pct', models.FloatField(blank=True, null=True)),
                ('off_2pt_made', models.FloatField(blank=True, null=True)),
                ('off_2pt_attempted', models.FloatField(blank=True, null=True)),
                ('off_2pt_pct', models.FloatField(blank=True, null=True)),
                ('off_3pt_made', models.FloatField(blank=True, null=True)),
                ('off_3pt_attempted', models.FloatField(blank=True, null=True)),
                ('off_3pt_pct', models.FloatField(blank=True, null=True)),
                ('off_ft_made', models.FloatField(blank=True, null=True)),
                ('off_ft_attempted', models.FloatField(blank=True, null=True)),
                ('off_ft_pct', models.FloatField(blank=True, null=True)),
                ('off_points', models.FloatField(blank=True, null=True)),
                ('off_assists', models.FloatField(blank=True, null=True)),
                ('off_steals', models.FloatField(blank=True, null=True)),
                ('off_blocks', models.FloatField(blank=True, null=True)),
                ('off_turnovers', models.FloatField(blank=True, null=True)),
                ('off_reb_total', models.FloatField(blank=True, null=True)),
                ('off_reb_offensive', models.FloatField(blank=True, null=True)),
                ('off_reb_defensive', models.FloatField(blank=True, null=True)),
                ('off_eff_fg_pct', models.FloatField(blank=True, null=True)),
                ('off_ft_rate', models.FloatField(blank=True, null=True)),
                ('off_oreb_pct', models.FloatField(blank=True, null=True)),
                ('off_turnover_ratio', models.FloatField(blank=True, null=True)),
                ('off_true_shooting', models.FloatField(blank=True, null=True)),
                ('off_rating', models.FloatField(blank=True, null=True)),
                ('off_possessions', models.FloatField(blank=True, null=True)),
                ('opp_fg_pct', models.FloatField(blank=True, null=True)),
                ('opp_2pt_pct', models.FloatField(blank=True, null=True)),
                ('opp_3pt_pct', models.FloatField(blank=True, null=True)),
                ('opp_ft_pct', models.FloatField(blank=True, null=True)),
                ('opp_points', models.FloatField(blank=True, null=True)),
                ('opp_assists', models.FloatField(blank=True, null=True)),
                ('opp_turnovers', models.FloatField(blank=True, null=True)),
                ('opp_reb_total', models.FloatField(blank=True, null=True)),
                ('opp_reb_offensive', models.FloatField(blank=True, null=True)),
                ('opp_eff_fg_pct', models.FloatField(blank=True, null=True)),
                ('opp_ft_rate', models.FloatField(blank=True, null=True)),
                ('opp_turnover_ratio', models.FloatField(blank=True, null=True)),
                ('opp_true_shooting', models.FloatField(blank=True, null=True)),
                ('opp_rating', models.FloatField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_stats', to='opencourt.team')),
            ],
            options={
                'ordering': ['-season'],
                'unique_together': {('team', 'season')},
            },
        ),
    ]
