# Generated by Django 6.0.2 on 2026-03-24 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencourt', '0005_game_gameteamstats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('season_type', models.CharField(blank=True, max_length=50, null=True)),
                ('week', models.IntegerField(blank=True, null=True)),
                ('poll_date', models.DateTimeField(blank=True, null=True)),
                ('poll_type', models.CharField(blank=True, max_length=100, null=True)),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('first_place_votes', models.IntegerField(blank=True, null=True)),
                ('conference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='opencourt.conference')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='opencourt.team')),
            ],
            options={
                'ordering': ['-season', '-week', 'ranking'],
                'unique_together': {('season', 'season_type', 'week', 'poll_type', 'team')},
            },
        ),
    ]
