# test_views.py — Integration tests for opencourt/views.py.
#
# Tests each view's HTTP response: status code, template used, and key
# context variables. Uses Django's test Client to make real requests
# against the test database — no mocking needed.
#
# Each test class targets one view. Tests create the minimum database
# state needed for the view to render successfully, then assert on the
# response.
#
# These tests hit the real ORM and template engine but NOT the CBBData
# API — views only read from the database, so no API mocking is required.
#
# Note: The predictions model file is not present in the test environment
# by default. Tests for UpcomingView mock make_predictions to avoid
# FileNotFoundError.
#
# Run just these tests:
#   uv run python manage.py test opencourt.tests.test_views

import json
from datetime import date, datetime, timedelta
from unittest.mock import patch

from django.test import TestCase, Client, override_settings
from django.urls import reverse
from django.utils import timezone

# ---------------------------------------------------------------------------
# Static files override
# ---------------------------------------------------------------------------
# In production, settings.py uses CompressedManifestStaticFilesStorage, which
# requires a staticfiles manifest generated by `collectstatic`. The test
# environment skips that step, so template rendering would crash on {% static %}
# tags. We override STORAGES here to use the basic StaticFilesStorage backend
# that doesn't need a manifest. This decorator is applied to every view test
# class below.
OVERRIDE_STORAGES = override_settings(STORAGES={
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
})

from opencourt.models import (
    Team, Conference, TeamSeasonStats, Game, GameTeamStats, Ranking,
)

# =============================================================================
# Test Data Factory Helpers
# =============================================================================
# These mirror test_models.py helpers but are self-contained so view tests
# don't depend on a separate module.

def _make_conference(**overrides):
    defaults = {
        'source_id': 1,
        'name': 'Atlantic Coast Conference',
        'abbrv': 'ACC',
        'short_name': 'ACC',
    }
    defaults.update(overrides)
    return Conference.objects.create(**defaults)

def _make_team(conference=None, **overrides):
    defaults = {
        'source_id': 150,
        'school': 'Duke',
        'abbrv': 'DUKE',
        'display_name': 'Duke Blue Devils',
        'short_display_name': 'Duke',
        'mascot': 'Blue Devils',
        'primary_color': '#001A57',
        'secondary_color': '#FFFFFF',
        'conference': conference,
    }
    defaults.update(overrides)
    return Team.objects.create(**defaults)

def _current_season_year():
    """Mirror of opencourt.views._current_season_year — defined locally so
    test factories don't need a Django app context to compute defaults.
    The DB stores `season` as the season's ending year (e.g. season=2026 ↔
    the 2025-26 season). Nov-Dec → today.year+1, Jan-Jun → today.year."""
    today = date.today()
    return today.year + 1 if today.month >= 7 else today.year


def _make_season_stats(team, **overrides):
    season_default = _current_season_year()
    defaults = {
        'team': team,
        'season': season_default,
        'season_label': f'{season_default}-{str(season_default + 1)[-2:]}',
        'games': 30,
        'wins': 20.0,
        'losses': 10.0,
        'pace': 68.5,
        'off_points': 2400.0,
        'opp_points': 2100.0,
        'off_rating': 112.5,
        'opp_rating': 98.3,
        'off_eff_fg_pct': 0.52,
        'off_turnover_ratio': 0.18,
        'off_oreb_pct': 0.32,
        'off_ft_rate': 0.35,
        'off_turnovers': 350.0,
        'off_possessions': 2000.0,
        'off_blocks': 120.0,
        'off_assists': 450.0,
        'off_fg_pct': 0.46,
        'off_3pt_pct': 0.36,
        'off_ft_pct': 0.75,
        'off_reb_total': 1100.0,
        'off_reb_offensive': 330.0,
    }
    defaults.update(overrides)
    return TeamSeasonStats.objects.create(**defaults)

def _make_game(home_team, away_team, **overrides):
    season_default = _current_season_year()
    defaults = {
        'source_id': 'game-001',
        'season': season_default,
        'season_label': f'{season_default}-{str(season_default + 1)[-2:]}',
        'season_type': 'regular',
        'status': 'final',
        'start_date': timezone.now(),
        'home_team': home_team,
        'away_team': away_team,
        'home_points': 78,
        'away_points': 72,
        'home_winner': True,
        'away_winner': False,
    }
    defaults.update(overrides)
    return Game.objects.create(**defaults)

def _make_ranking(team, **overrides):
    defaults = {
        'team': team,
        'season': date.today().year,
        'season_type': 'regular',
        'week': 10,
        'poll_type': 'AP Top 25',
        'poll_date': timezone.now(),
        'ranking': 1,
        'points': 1500,
        'first_place_votes': 60,
    }
    defaults.update(overrides)
    return Ranking.objects.create(**defaults)

# =============================================================================
# HomeView Tests
# =============================================================================

@OVERRIDE_STORAGES
class HomeViewTest(TestCase):
    """
    Tests for HomeView (GET /).

    The landing page shows top-5 teams by win%, 3 featured conferences,
    and platform-wide counts (teams, conferences, games).
    """

    def test_status_200(self):
        """Home page should return HTTP 200 for any request."""
        response = self.client.get(reverse('opencourt:home'))
        self.assertEqual(response.status_code, 200)

    def test_correct_template(self):
        """Home page should render the opencourt/home.html template."""
        response = self.client.get(reverse('opencourt:home'))
        self.assertTemplateUsed(response, 'opencourt/home.html')

    def test_empty_database(self):
        """
        Home page should render without errors when the database is empty
        (no teams, conferences, or games). This is the first-run state
        before sync_data has been executed.
        """
        response = self.client.get(reverse('opencourt:home'))
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.context['total_teams'], 0)
        self.assertEqual(response.context['total_conferences'], 0)
        self.assertEqual(response.context['total_games'], 0)

    def test_top_teams_limited_to_five(self):
        """
        top_teams in context should contain at most 5 teams, even when
        more teams with stats exist in the database.
        """
        conf = _make_conference()
        for i in range(8):
            team = _make_team(
                conference=conf,
                source_id=i,
                school=f'Team{i}',
                mascot=f'Mascot{i}',
                slug=f'team-{i}',
            )
            _make_season_stats(team, wins=20.0 + i, losses=10.0)

        response = self.client.get(reverse('opencourt:home'))
        self.assertLessEqual(len(response.context['top_teams']), 5)

    def test_platform_stats_counts(self):
        """Context should include accurate counts for teams, conferences, games."""
        conf = _make_conference()
        team1 = _make_team(conference=conf, source_id=1, slug='t1', school='T1', mascot='M1')
        team2 = _make_team(conference=conf, source_id=2, slug='t2', school='T2', mascot='M2')
        # HomeView filters total_games by season=date.today().year (calendar
        # year, not CBB season). The factory defaults to _current_season_year()
        # which differs from today.year between Jan and Jun, so override it
        # here to match HomeView's filter.
        _make_game(team1, team2, season=date.today().year)

        response = self.client.get(reverse('opencourt:home'))
        self.assertEqual(response.context['total_teams'], 2)
        self.assertEqual(response.context['total_conferences'], 1)
        self.assertEqual(response.context['total_games'], 1)

# =============================================================================
# AboutView Tests
# =============================================================================

@OVERRIDE_STORAGES
class AboutViewTest(TestCase):
    """
    Tests for AboutView (GET /about/).

    This is a static page with no model data — just verify it renders.
    """

    def test_status_200(self):
        """About page should return HTTP 200."""
        response = self.client.get(reverse('opencourt:about'))
        self.assertEqual(response.status_code, 200)

    def test_correct_template(self):
        """About page should render the opencourt/about.html template."""
        response = self.client.get(reverse('opencourt:about'))
        self.assertTemplateUsed(response, 'opencourt/about.html')

# =============================================================================
# TeamListView Tests
# =============================================================================

@OVERRIDE_STORAGES
class TeamListViewTest(TestCase):
    """
    Tests for TeamListView (GET /teams/).

    Displays all ~360 D1 teams in an alphabetically sorted list with
    a conference filter dropdown.
    """

    def test_status_200(self):
        """Teams page should return HTTP 200."""
        response = self.client.get(reverse('opencourt:teams'))
        self.assertEqual(response.status_code, 200)

    def test_correct_template(self):
        """Teams page should use the opencourt/teams.html template."""
        response = self.client.get(reverse('opencourt:teams'))
        self.assertTemplateUsed(response, 'opencourt/teams.html')

    def test_empty_database(self):
        """Teams page should render with an empty team list when no teams exist."""
        response = self.client.get(reverse('opencourt:teams'))
        self.assertEqual(response.status_code, 200)
        self.assertEqual(len(response.context['team_list']), 0)

    def test_teams_in_context(self):
        """All created teams should appear in the team_list context variable."""
        conf = _make_conference()
        _make_team(conference=conf, source_id=1, school='Duke', mascot='BD', slug='duke')
        _make_team(conference=conf, source_id=2, school='UNC', mascot='TH', slug='unc')

        response = self.client.get(reverse('opencourt:teams'))
        self.assertEqual(len(response.context['team_list']), 2)

    def test_teams_ordered_alphabetically(self):
        """Teams should be ordered by school name (A-Z)."""
        conf = _make_conference()
        _make_team(conference=conf, source_id=1, school='Zion', mascot='Z', slug='zion')
        _make_team(conference=conf, source_id=2, school='Alabama', mascot='A', slug='alabama')

        response = self.client.get(reverse('opencourt:teams'))
        schools = [t.school for t in response.context['team_list']]
        self.assertEqual(schools, ['Alabama', 'Zion'])

    def test_conference_list_in_context(self):
        """Context should include conference_list for the filter dropdown."""
        _make_conference()
        response = self.client.get(reverse('opencourt:teams'))
        self.assertIn('conference_list', response.context)
        self.assertEqual(len(response.context['conference_list']), 1)

# =============================================================================
# ConferenceListView Tests
# =============================================================================

@OVERRIDE_STORAGES
class ConferenceListViewTest(TestCase):
    """
    Tests for ConferenceListView (GET /conferences/).

    Two-panel layout: sidebar of conferences, right panel with teams
    and aggregate stats (team_count, avg_win_pct, total_wins, total_losses).
    """

    def test_status_200(self):
        """Conferences page should return HTTP 200."""
        response = self.client.get(reverse('opencourt:conferences'))
        self.assertEqual(response.status_code, 200)

    def test_correct_template(self):
        """Conferences page should use opencourt/conferences.html."""
        response = self.client.get(reverse('opencourt:conferences'))
        self.assertTemplateUsed(response, 'opencourt/conferences.html')

    def test_empty_database(self):
        """Page should render when no conferences exist."""
        response = self.client.get(reverse('opencourt:conferences'))
        self.assertEqual(response.status_code, 200)

    def test_conference_annotations(self):
        """
        Each conference in the queryset should be annotated with team_count.
        Verify the annotation is present and correct.
        """
        conf = _make_conference()
        _make_team(conference=conf, source_id=1, school='T1', mascot='M1', slug='t1')
        _make_team(conference=conf, source_id=2, school='T2', mascot='M2', slug='t2')

        response = self.client.get(reverse('opencourt:conferences'))
        conf_obj = response.context['conference_list'][0]
        self.assertEqual(conf_obj.team_count, 2)

# =============================================================================
# RankingsListView Tests
# =============================================================================

@OVERRIDE_STORAGES
class RankingsListViewTest(TestCase):
    """
    Tests for RankingsListView (GET /rankings/).

    Displays AP Top 25 and Coaches Poll side by side with week
    navigation via the ?week=N query parameter.
    """

    def setUp(self):
        """Create teams and rankings for testing week navigation."""
        self.conf = _make_conference()
        self.team = _make_team(conference=self.conf)
        _make_season_stats(self.team)

    def test_status_200(self):
        """Rankings page should return HTTP 200."""
        response = self.client.get(reverse('opencourt:rankings'))
        self.assertEqual(response.status_code, 200)

    def test_correct_template(self):
        """Rankings page should use opencourt/rankings.html."""
        response = self.client.get(reverse('opencourt:rankings'))
        self.assertTemplateUsed(response, 'opencourt/rankings.html')

    def test_empty_database(self):
        """Page should render when no rankings exist (preseason / early season)."""
        response = self.client.get(reverse('opencourt:rankings'))
        self.assertEqual(response.status_code, 200)

    def test_week_param_selects_correct_week(self):
        """
        Passing ?week=5 should set selected_week to 5 in context.
        """
        _make_ranking(self.team, week=5, poll_type='AP Top 25')
        response = self.client.get(reverse('opencourt:rankings') + '?week=5')
        self.assertEqual(response.context['selected_week'], 5)

    def test_invalid_week_param_falls_back(self):
        """
        Passing ?week=abc (non-integer) should fall back to the most
        recent week rather than crashing.
        """
        _make_ranking(self.team, week=10, poll_type='AP Top 25')
        response = self.client.get(reverse('opencourt:rankings') + '?week=abc')
        self.assertEqual(response.status_code, 200)
        # Should fall back to most recent week (10)
        self.assertEqual(response.context['selected_week'], 10)

    def test_available_weeks_in_context(self):
        """
        Context should include available_weeks list for the week dropdown,
        ordered newest-first.
        """
        _make_ranking(self.team, week=5, poll_type='AP Top 25')
        _make_ranking(self.team, week=10, poll_type='AP Top 25',
                      poll_date=timezone.now() + timedelta(weeks=5))

        response = self.client.get(reverse('opencourt:rankings'))
        weeks = [w['week'] for w in response.context['available_weeks']]
        self.assertEqual(weeks, [10, 5])

    def test_conference_list_in_context(self):
        """Context should include conference_list for the filter dropdown."""
        response = self.client.get(reverse('opencourt:rankings'))
        self.assertIn('conference_list', response.context)

# =============================================================================
# TeamDetailView Tests
# =============================================================================

@OVERRIDE_STORAGES
class TeamDetailViewTest(TestCase):
    """
    Tests for TeamDetailView (GET /<slug>/).

    The team detail page shows historical stats as ApexCharts, a current
    season schedule with expandable box scores, and team metadata.
    """

    def setUp(self):
        """Create a team with season stats and a game for testing."""
        self.conf = _make_conference()
        self.team = _make_team(conference=self.conf, slug='duke-blue-devils')
        self.stats = _make_season_stats(self.team)

    def test_status_200(self):
        """Team detail page should return HTTP 200 for a valid slug."""
        response = self.client.get(
            reverse('opencourt:team-detail', kwargs={'slug': 'duke-blue-devils'})
        )
        self.assertEqual(response.status_code, 200)

    def test_correct_template(self):
        """Team detail should use opencourt/team_details.html."""
        response = self.client.get(
            reverse('opencourt:team-detail', kwargs={'slug': 'duke-blue-devils'})
        )
        self.assertTemplateUsed(response, 'opencourt/team_details.html')

    def test_invalid_slug_returns_404(self):
        """A non-existent slug should return HTTP 404."""
        response = self.client.get(
            reverse('opencourt:team-detail', kwargs={'slug': 'nonexistent-team'})
        )
        self.assertEqual(response.status_code, 404)

    def test_team_in_context(self):
        """Context should contain the correct team object."""
        response = self.client.get(
            reverse('opencourt:team-detail', kwargs={'slug': 'duke-blue-devils'})
        )
        self.assertEqual(response.context['team'].pk, self.team.pk)

    def test_chart_data_is_valid_json(self):
        """
        Chart data context variables (stat_years, wins, losses, etc.) should
        be valid JSON strings that JavaScript can parse.
        """
        response = self.client.get(
            reverse('opencourt:team-detail', kwargs={'slug': 'duke-blue-devils'})
        )
        # These should be valid JSON arrays
        for key in ['stat_years', 'wins', 'losses', 'win_pct', 'off_rtg', 'opp_rtg']:
            try:
                parsed = json.loads(response.context[key])
                self.assertIsInstance(parsed, list)
            except (json.JSONDecodeError, KeyError) as e:
                self.fail(f"Context key '{key}' is not valid JSON: {e}")

    def test_team_with_no_stats(self):
        """
        A team with no season stats should still render — chart arrays
        should be empty JSON lists.
        """
        empty_team = _make_team(
            source_id=999, school='NewTeam', mascot='Mascot', slug='new-team'
        )
        response = self.client.get(
            reverse('opencourt:team-detail', kwargs={'slug': 'new-team'})
        )
        self.assertEqual(response.status_code, 200)
        self.assertEqual(json.loads(response.context['wins']), [])

    def test_schedule_in_context(self):
        """
        Context should include a 'schedule' list. Each entry has 'game',
        'is_home', 'opponent', 'team_points', 'opp_points', 'won'.
        """
        opp = _make_team(source_id=2, school='UNC', mascot='TH', slug='unc')
        _make_game(
            self.team, opp,
            season=date.today().year,
            start_date=timezone.now(),
        )

        response = self.client.get(
            reverse('opencourt:team-detail', kwargs={'slug': 'duke-blue-devils'})
        )
        schedule = response.context['schedule']
        self.assertEqual(len(schedule), 1)
        self.assertTrue(schedule[0]['is_home'])
        self.assertEqual(schedule[0]['opponent'].pk, opp.pk)
        self.assertEqual(schedule[0]['team_points'], 78)
        self.assertEqual(schedule[0]['opp_points'], 72)

# =============================================================================
# UpcomingView Tests
# =============================================================================
#
# UpcomingView dispatches between two views via the ?view= GET param:
#   ?view=calendar (default) — monthly calendar grid (predictions_calendar.html)
#   ?view=list                — original head-to-head card grid (head_head.html)
#
# The calendar view is the new default; the list view is the original
# pre-calendar behavior preserved behind the toggle.
#
# Predictions require the ML model file, which doesn't exist in the test
# environment. _get_predict_model() returns None when the file is missing,
# and both _predict_home_win and _batch_predict_home_wins short-circuit on
# pred_model is None — so no mocking is needed for the view to render.

@OVERRIDE_STORAGES
class UpcomingViewTest(TestCase):
    """
    Tests for UpcomingView (GET /upcoming/) — the dispatcher itself.

    Verifies the ?view= toggle picks the right template and context.
    Calendar-specific and list-specific assertions live in the dedicated
    sub-test-classes below.
    """

    def setUp(self):
        self.conf = _make_conference()
        self.home = _make_team(
            conference=self.conf, source_id=1, school='Duke',
            mascot='BD', slug='duke'
        )
        self.away = _make_team(
            conference=self.conf, source_id=2, school='UNC',
            mascot='TH', slug='unc'
        )
        current_year = _current_season_year()
        _make_season_stats(self.home, season=current_year)
        _make_season_stats(self.away, season=current_year)

    # ── Dispatch / toggle ────────────────────────────────────────────────

    def test_status_200_default(self):
        """Page should return HTTP 200 with no params (defaults to calendar)."""
        response = self.client.get(reverse('opencourt:upcoming'))
        self.assertEqual(response.status_code, 200)

    def test_default_view_is_calendar(self):
        """No ?view= param → calendar view + predictions_calendar.html."""
        response = self.client.get(reverse('opencourt:upcoming'))
        self.assertEqual(response.context['view_mode'], 'calendar')
        self.assertTemplateUsed(response, 'opencourt/predictions_calendar.html')

    def test_view_calendar_explicit(self):
        """?view=calendar → calendar template."""
        response = self.client.get(reverse('opencourt:upcoming') + '?view=calendar')
        self.assertEqual(response.context['view_mode'], 'calendar')
        self.assertTemplateUsed(response, 'opencourt/predictions_calendar.html')

    def test_view_list(self):
        """?view=list → head_head.html template + view_mode='list'."""
        response = self.client.get(reverse('opencourt:upcoming') + '?view=list')
        self.assertEqual(response.context['view_mode'], 'list')
        self.assertTemplateUsed(response, 'opencourt/head_head.html')

    def test_unknown_view_falls_back_to_calendar(self):
        """?view=garbage should fall back to calendar (the safe default)."""
        response = self.client.get(reverse('opencourt:upcoming') + '?view=garbage')
        self.assertEqual(response.context['view_mode'], 'calendar')
        self.assertTemplateUsed(response, 'opencourt/predictions_calendar.html')


@OVERRIDE_STORAGES
class UpcomingViewCalendarTest(TestCase):
    """Tests scoped to the ?view=calendar context shape."""

    def setUp(self):
        self.conf = _make_conference()
        self.home = _make_team(
            conference=self.conf, source_id=1, school='Duke',
            mascot='BD', slug='duke'
        )
        self.away = _make_team(
            conference=self.conf, source_id=2, school='UNC',
            mascot='TH', slug='unc'
        )
        current_year = _current_season_year()
        _make_season_stats(self.home, season=current_year)
        _make_season_stats(self.away, season=current_year)

    # ── Context shape ───────────────────────────────────────────────────

    def test_required_context_keys(self):
        """Calendar context should expose the keys the template depends on."""
        response = self.client.get(reverse('opencourt:upcoming'))
        for key in (
            'weeks', 'modal_days', 'pill_cap',
            'year', 'month', 'month_name',
            'prev_year', 'prev_month', 'next_year', 'next_month',
            'today', 'season_year', 'is_current_month',
            'accuracy', 'weekday_labels',
        ):
            self.assertIn(key, response.context, f'missing context key: {key}')

    def test_default_year_month_is_today(self):
        """Without params, year/month default to today."""
        response = self.client.get(reverse('opencourt:upcoming'))
        today = date.today()
        self.assertEqual(response.context['year'], today.year)
        self.assertEqual(response.context['month'], today.month)
        self.assertTrue(response.context['is_current_month'])

    def test_year_month_params(self):
        """?year= & ?month= should select that month."""
        response = self.client.get(
            reverse('opencourt:upcoming') + '?year=2025&month=11'
        )
        self.assertEqual(response.context['year'], 2025)
        self.assertEqual(response.context['month'], 11)
        self.assertEqual(response.context['month_name'], 'November')

    def test_invalid_month_falls_back(self):
        """?month=99 should fall back to today's month, not 500."""
        response = self.client.get(
            reverse('opencourt:upcoming') + '?month=99'
        )
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.context['month'], date.today().month)

    def test_invalid_year_falls_back(self):
        """?year=abc should fall back to today's year."""
        response = self.client.get(
            reverse('opencourt:upcoming') + '?year=abc'
        )
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.context['year'], date.today().year)

    def test_out_of_range_year_falls_back(self):
        """?year=1500 should clamp to today's year (defends against runaway grids)."""
        response = self.client.get(
            reverse('opencourt:upcoming') + '?year=1500'
        )
        self.assertEqual(response.context['year'], date.today().year)

    # ── Grid structure ──────────────────────────────────────────────────

    def test_weeks_grid_shape(self):
        """`weeks` should be a list of weeks; each week is 7 day-cells."""
        response = self.client.get(reverse('opencourt:upcoming'))
        weeks = response.context['weeks']
        # monthdatescalendar() always returns full weeks (Sun..Sat) so each
        # row must contain exactly 7 cells. The number of weeks varies with
        # the month (4-6) so we assert >= 4 rather than a fixed count.
        self.assertGreaterEqual(len(weeks), 4)
        self.assertLessEqual(len(weeks), 6)
        for week in weeks:
            self.assertEqual(len(week), 7)
        # Cell shape
        cell = weeks[0][0]
        for key in ('date', 'in_month', 'is_today',
                    'games', 'visible_games', 'overflow_count', 'modal_id'):
            self.assertIn(key, cell)

    def test_pill_cap_exposed(self):
        """pill_cap must equal UpcomingView.CAL_PILL_CAP."""
        from opencourt.views import UpcomingView
        response = self.client.get(reverse('opencourt:upcoming'))
        self.assertEqual(response.context['pill_cap'], UpcomingView.CAL_PILL_CAP)

    def test_weekday_labels_seven_items_sunday_first(self):
        """Weekday header is Sun-first and has 7 entries."""
        response = self.client.get(reverse('opencourt:upcoming'))
        labels = response.context['weekday_labels']
        self.assertEqual(len(labels), 7)
        self.assertEqual(labels[0], 'Sun')

    # ── Game grouping & status coloring ─────────────────────────────────

    def test_completed_game_in_grid(self):
        """A finished game falls into its calendar-day cell."""
        from opencourt.views import UpcomingView
        today = date.today()
        # Use a fixed mid-day timestamp so timezone localization can't shift
        # the game off the test's expected date.
        when = timezone.make_aware(datetime.combine(today, datetime.min.time())
                                   + timedelta(hours=15))
        _make_game(
            self.home, self.away,
            source_id='played-1',
            status='final',
            start_date=when,
            home_winner=True,
            away_winner=False,
        )

        response = self.client.get(reverse('opencourt:upcoming'))
        weeks = response.context['weeks']
        # Locate today's cell
        cell = None
        for week in weeks:
            for c in week:
                if c['date'] == today:
                    cell = c
                    break
        self.assertIsNotNone(cell)
        self.assertEqual(len(cell['games']), 1)
        # Without the model file the prediction is unavailable, so a played
        # game shows as 'no_prediction' (rendered as the neutral pill).
        self.assertIn(cell['games'][0]['status'],
                      ('correct', 'incorrect', 'no_prediction'))

    def test_unplayed_game_status(self):
        """A scheduled future game gets status='unplayed'."""
        today = date.today()
        when = timezone.make_aware(datetime.combine(today, datetime.min.time())
                                   + timedelta(hours=15))
        _make_game(
            self.home, self.away,
            source_id='scheduled-1',
            status='scheduled',
            start_date=when,
            home_points=None,
            away_points=None,
            home_winner=None,
            away_winner=None,
        )
        response = self.client.get(reverse('opencourt:upcoming'))
        statuses = [
            g['status']
            for week in response.context['weeks']
            for cell in week
            for g in cell['games']
        ]
        self.assertIn('unplayed', statuses)

    # ── Overflow / modal ────────────────────────────────────────────────

    def test_overflow_pills_collapse_into_modal(self):
        """A day with more than CAL_PILL_CAP games produces a modal entry."""
        from opencourt.views import UpcomingView
        today = date.today()
        # Build (CAP + 3) games on today so we provoke an overflow.
        # We need (CAP + 3) team pairs with stats; reuse self.home/self.away
        # and create extra teams for additional matchups.
        n = UpcomingView.CAL_PILL_CAP + 3
        for i in range(n):
            home = _make_team(
                conference=self.conf, source_id=100 + i,
                school=f'H{i}', mascot=f'M{i}', slug=f'h-{i}'
            )
            away = _make_team(
                conference=self.conf, source_id=200 + i,
                school=f'A{i}', mascot=f'M{i}', slug=f'a-{i}'
            )
            when = timezone.make_aware(
                datetime.combine(today, datetime.min.time()) + timedelta(hours=15)
            )
            _make_game(
                home, away,
                source_id=f'busy-{i}',
                status='scheduled',
                start_date=when,
                home_points=None, away_points=None,
                home_winner=None, away_winner=None,
            )

        response = self.client.get(reverse('opencourt:upcoming'))
        # modal_days should contain today
        modal_dates = [m['date'] for m in response.context['modal_days']]
        self.assertIn(today, modal_dates)
        # Today's cell should mark CAL_PILL_CAP visible + (n - CAP) overflow
        for week in response.context['weeks']:
            for cell in week:
                if cell['date'] == today:
                    self.assertEqual(len(cell['visible_games']), UpcomingView.CAL_PILL_CAP)
                    self.assertEqual(cell['overflow_count'],
                                     n - UpcomingView.CAL_PILL_CAP)

    def test_no_modal_when_under_pill_cap(self):
        """Days with ≤ CAP games shouldn't generate modal entries."""
        from opencourt.views import UpcomingView
        today = date.today()
        when = timezone.make_aware(
            datetime.combine(today, datetime.min.time()) + timedelta(hours=15)
        )
        _make_game(
            self.home, self.away,
            source_id='lone-1',
            status='scheduled',
            start_date=when,
            home_points=None, away_points=None,
            home_winner=None, away_winner=None,
        )
        response = self.client.get(reverse('opencourt:upcoming'))
        # 1 game ≤ CAP → no modal for today.
        modal_dates = [m['date'] for m in response.context['modal_days']]
        self.assertNotIn(today, modal_dates)


@OVERRIDE_STORAGES
class UpcomingViewListTest(TestCase):
    """Tests scoped to the ?view=list head-to-head card grid."""

    def setUp(self):
        self.conf = _make_conference()
        self.home = _make_team(
            conference=self.conf, source_id=1, school='Duke',
            mascot='BD', slug='duke'
        )
        self.away = _make_team(
            conference=self.conf, source_id=2, school='UNC',
            mascot='TH', slug='unc'
        )
        current_year = _current_season_year()
        _make_season_stats(self.home, season=current_year)
        _make_season_stats(self.away, season=current_year)

    # ── Sub-mode selection (upcoming / results) ─────────────────────────

    def test_default_mode_is_upcoming(self):
        """?view=list (no ?mode) defaults to mode='upcoming'."""
        response = self.client.get(reverse('opencourt:upcoming') + '?view=list')
        self.assertEqual(response.context['mode'], 'upcoming')

    def test_results_mode(self):
        """?view=list&mode=results sets context['mode'] = 'results'."""
        response = self.client.get(
            reverse('opencourt:upcoming') + '?view=list&mode=results'
        )
        self.assertEqual(response.context['mode'], 'results')

    def test_invalid_mode_falls_back_to_upcoming(self):
        """?mode=garbage falls back to 'upcoming' (preserves old behavior)."""
        response = self.client.get(
            reverse('opencourt:upcoming') + '?view=list&mode=garbage'
        )
        self.assertEqual(response.context['mode'], 'upcoming')

    # ── Game enrichment ─────────────────────────────────────────────────

    def test_upcoming_shows_future_games(self):
        """In upcoming mode, scheduled future games appear in context."""
        tomorrow = timezone.now() + timedelta(days=1)
        _make_game(
            self.home, self.away,
            source_id='future-1',
            status='scheduled',
            start_date=tomorrow,
            home_points=None, away_points=None,
            home_winner=None, away_winner=None,
        )
        response = self.client.get(
            reverse('opencourt:upcoming') + '?view=list&mode=upcoming&date=all'
        )
        self.assertEqual(response.status_code, 200)
        total_games = len(response.context['games']) + len(response.context['all_games'])
        self.assertGreaterEqual(total_games, 1)

    def test_results_mode_shows_completed_games(self):
        """In results mode, completed games appear with an accuracy banner."""
        _make_game(
            self.home, self.away,
            source_id='completed-1',
            status='final',
            start_date=timezone.now(),
            home_winner=True,
            away_winner=False,
        )
        response = self.client.get(
            reverse('opencourt:upcoming') + '?view=list&mode=results&date=all'
        )
        self.assertEqual(response.status_code, 200)
        self.assertIn('accuracy', response.context)

    # ── Date filtering ──────────────────────────────────────────────────

    def test_date_param_invalid_falls_back(self):
        """?date=not-a-date should fall back to today without crashing."""
        response = self.client.get(
            reverse('opencourt:upcoming') + '?view=list&date=not-a-date'
        )
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.context['selected_date'], date.today())

    def test_show_all_flag(self):
        """?date=all should set show_all=True and selected_date=None."""
        response = self.client.get(
            reverse('opencourt:upcoming') + '?view=list&date=all'
        )
        self.assertEqual(response.status_code, 200)
        self.assertTrue(response.context['show_all'])
        self.assertIsNone(response.context['selected_date'])

    def test_upcoming_dates_in_context(self):
        """upcoming_dates is a list of 7 date objects for the date tabs."""
        response = self.client.get(reverse('opencourt:upcoming') + '?view=list')
        self.assertEqual(len(response.context['upcoming_dates']), 7)


@OVERRIDE_STORAGES
class UpcomingViewCrossViewConsistencyTest(TestCase):
    """
    Regression test for the season_year mismatch bug: the same completed
    game must show the same correct/incorrect status in both the calendar
    view and the list view. Previously the list view used today.year+1/
    today.year while the calendar used year/year-1 — different season_year
    → different prefetched stats → different model features → different
    predictions for the same game.
    """

    def setUp(self):
        self.conf = _make_conference()
        self.home = _make_team(
            conference=self.conf, source_id=1, school='UConn',
            mascot='Huskies', slug='uconn'
        )
        self.away = _make_team(
            conference=self.conf, source_id=2, school='Michigan',
            mascot='Wolverines', slug='michigan'
        )
        # Use the season_year the new (fixed) helper resolves to so the
        # game falls into both querysets — calendar (date-filtered to its
        # month) and list (filtered by season=N).
        from opencourt.views import _current_season_year
        season = _current_season_year()
        _make_season_stats(self.home, season=season)
        _make_season_stats(self.away, season=season)

        # Create a finished game in the current season. Pick a mid-day
        # time so timezone localization can't push the date around.
        today = date.today()
        when = timezone.make_aware(
            datetime.combine(today, datetime.min.time()) + timedelta(hours=15)
        )
        self.game = _make_game(
            self.home, self.away,
            source_id='cross-view-1',
            season=season,
            status='final',
            start_date=when,
            home_winner=True,
            away_winner=False,
            home_points=78,
            away_points=72,
        )

    def test_same_game_same_status_in_both_views(self):
        """
        Pull the same game from the calendar context and the list context
        and assert they agree on prediction_correct (or both no_prediction).
        """
        # Calendar — find this game in today's cell.
        cal_resp = self.client.get(reverse('opencourt:upcoming'))
        cal_status = None
        today = date.today()
        for week in cal_resp.context['weeks']:
            for cell in week:
                if cell['date'] == today:
                    for g in cell['games']:
                        if g['game'].id == self.game.id:
                            cal_status = g['status']
                            break
        self.assertIsNotNone(cal_status,
                             'game not found in calendar today cell')

        # List — find this game in all_games (the global search pool).
        list_resp = self.client.get(
            reverse('opencourt:upcoming') + '?view=list&mode=results&date=all'
        )
        list_correct = None
        for item in list_resp.context['all_games']:
            if item['game'].id == self.game.id:
                list_correct = item['prediction_correct']
                break
        # The game should be in the list view's pool too.
        self.assertTrue(
            any(item['game'].id == self.game.id
                for item in list_resp.context['all_games']),
            'game not found in list view all_games pool',
        )

        # Both views map cal_status → list_correct as follows:
        #   'correct'        ↔ list_correct == True
        #   'incorrect'      ↔ list_correct == False
        #   'no_prediction'  ↔ list_correct is None
        expected = {
            'correct': True,
            'incorrect': False,
            'no_prediction': None,
        }[cal_status]
        self.assertEqual(
            list_correct, expected,
            f'calendar says {cal_status!r} but list says '
            f'prediction_correct={list_correct!r}'
        )
