# test_views.py — Integration tests for opencourt/views.py.
#
# Tests each view's HTTP response: status code, template used, and key
# context variables. Uses Django's test Client to make real requests
# against the test database — no mocking needed.
#
# Each test class targets one view. Tests create the minimum database
# state needed for the view to render successfully, then assert on the
# response.
#
# These tests hit the real ORM and template engine but NOT the CBBData
# API — views only read from the database, so no API mocking is required.
#
# Note: The predictions model file is not present in the test environment
# by default. Tests for UpcomingView mock make_predictions to avoid
# FileNotFoundError.
#
# Run just these tests:
#   uv run python manage.py test opencourt.tests.test_views

import json
from datetime import date, datetime, timedelta
from unittest.mock import patch

from django.test import TestCase, Client, override_settings
from django.urls import reverse
from django.utils import timezone

# ---------------------------------------------------------------------------
# Static files override
# ---------------------------------------------------------------------------
# In production, settings.py uses CompressedManifestStaticFilesStorage, which
# requires a staticfiles manifest generated by `collectstatic`. The test
# environment skips that step, so template rendering would crash on {% static %}
# tags. We override STORAGES here to use the basic StaticFilesStorage backend
# that doesn't need a manifest. This decorator is applied to every view test
# class below.
OVERRIDE_STORAGES = override_settings(STORAGES={
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
})

from opencourt.models import (
    Team, Conference, TeamSeasonStats, Game, GameTeamStats, Ranking,
)

# =============================================================================
# Test Data Factory Helpers
# =============================================================================
# These mirror test_models.py helpers but are self-contained so view tests
# don't depend on a separate module.

def _make_conference(**overrides):
    defaults = {
        'source_id': 1,
        'name': 'Atlantic Coast Conference',
        'abbrv': 'ACC',
        'short_name': 'ACC',
    }
    defaults.update(overrides)
    return Conference.objects.create(**defaults)

def _make_team(conference=None, **overrides):
    defaults = {
        'source_id': 150,
        'school': 'Duke',
        'abbrv': 'DUKE',
        'display_name': 'Duke Blue Devils',
        'short_display_name': 'Duke',
        'mascot': 'Blue Devils',
        'primary_color': '#001A57',
        'secondary_color': '#FFFFFF',
        'conference': conference,
    }
    defaults.update(overrides)
    return Team.objects.create(**defaults)

def _make_season_stats(team, **overrides):
    defaults = {
        'team': team,
        'season': date.today().year,
        'season_label': f'{date.today().year}-{str(date.today().year + 1)[-2:]}',
        'games': 30,
        'wins': 20.0,
        'losses': 10.0,
        'pace': 68.5,
        'off_points': 2400.0,
        'opp_points': 2100.0,
        'off_rating': 112.5,
        'opp_rating': 98.3,
        'off_eff_fg_pct': 0.52,
        'off_turnover_ratio': 0.18,
        'off_oreb_pct': 0.32,
        'off_ft_rate': 0.35,
        'off_turnovers': 350.0,
        'off_possessions': 2000.0,
        'off_blocks': 120.0,
        'off_assists': 450.0,
        'off_fg_pct': 0.46,
        'off_3pt_pct': 0.36,
        'off_ft_pct': 0.75,
        'off_reb_total': 1100.0,
        'off_reb_offensive': 330.0,
    }
    defaults.update(overrides)
    return TeamSeasonStats.objects.create(**defaults)

def _make_game(home_team, away_team, **overrides):
    defaults = {
        'source_id': 'game-001',
        'season': date.today().year,
        'season_label': f'{date.today().year}-{str(date.today().year + 1)[-2:]}',
        'season_type': 'regular',
        'status': 'final',
        'start_date': timezone.now(),
        'home_team': home_team,
        'away_team': away_team,
        'home_points': 78,
        'away_points': 72,
        'home_winner': True,
        'away_winner': False,
    }
    defaults.update(overrides)
    return Game.objects.create(**defaults)

def _make_ranking(team, **overrides):
    defaults = {
        'team': team,
        'season': date.today().year,
        'season_type': 'regular',
        'week': 10,
        'poll_type': 'AP Top 25',
        'poll_date': timezone.now(),
        'ranking': 1,
        'points': 1500,
        'first_place_votes': 60,
    }
    defaults.update(overrides)
    return Ranking.objects.create(**defaults)

# =============================================================================
# HomeView Tests
# =============================================================================

@OVERRIDE_STORAGES
class HomeViewTest(TestCase):
    """
    Tests for HomeView (GET /).

    The landing page shows top-5 teams by win%, 3 featured conferences,
    and platform-wide counts (teams, conferences, games).
    """

    def test_status_200(self):
        """Home page should return HTTP 200 for any request."""
        response = self.client.get(reverse('opencourt:home'))
        self.assertEqual(response.status_code, 200)

    def test_correct_template(self):
        """Home page should render the opencourt/home.html template."""
        response = self.client.get(reverse('opencourt:home'))
        self.assertTemplateUsed(response, 'opencourt/home.html')

    def test_empty_database(self):
        """
        Home page should render without errors when the database is empty
        (no teams, conferences, or games). This is the first-run state
        before sync_data has been executed.
        """
        response = self.client.get(reverse('opencourt:home'))
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.context['total_teams'], 0)
        self.assertEqual(response.context['total_conferences'], 0)
        self.assertEqual(response.context['total_games'], 0)

    def test_top_teams_limited_to_five(self):
        """
        top_teams in context should contain at most 5 teams, even when
        more teams with stats exist in the database.
        """
        conf = _make_conference()
        for i in range(8):
            team = _make_team(
                conference=conf,
                source_id=i,
                school=f'Team{i}',
                mascot=f'Mascot{i}',
                slug=f'team-{i}',
            )
            _make_season_stats(team, wins=20.0 + i, losses=10.0)

        response = self.client.get(reverse('opencourt:home'))
        self.assertLessEqual(len(response.context['top_teams']), 5)

    def test_platform_stats_counts(self):
        """Context should include accurate counts for teams, conferences, games."""
        conf = _make_conference()
        team1 = _make_team(conference=conf, source_id=1, slug='t1', school='T1', mascot='M1')
        team2 = _make_team(conference=conf, source_id=2, slug='t2', school='T2', mascot='M2')
        _make_game(team1, team2)

        response = self.client.get(reverse('opencourt:home'))
        self.assertEqual(response.context['total_teams'], 2)
        self.assertEqual(response.context['total_conferences'], 1)
        self.assertEqual(response.context['total_games'], 1)

# =============================================================================
# AboutView Tests
# =============================================================================

@OVERRIDE_STORAGES
class AboutViewTest(TestCase):
    """
    Tests for AboutView (GET /about/).

    This is a static page with no model data — just verify it renders.
    """

    def test_status_200(self):
        """About page should return HTTP 200."""
        response = self.client.get(reverse('opencourt:about'))
        self.assertEqual(response.status_code, 200)

    def test_correct_template(self):
        """About page should render the opencourt/about.html template."""
        response = self.client.get(reverse('opencourt:about'))
        self.assertTemplateUsed(response, 'opencourt/about.html')

# =============================================================================
# TeamListView Tests
# =============================================================================

@OVERRIDE_STORAGES
class TeamListViewTest(TestCase):
    """
    Tests for TeamListView (GET /teams/).

    Displays all ~360 D1 teams in an alphabetically sorted list with
    a conference filter dropdown.
    """

    def test_status_200(self):
        """Teams page should return HTTP 200."""
        response = self.client.get(reverse('opencourt:teams'))
        self.assertEqual(response.status_code, 200)

    def test_correct_template(self):
        """Teams page should use the opencourt/teams.html template."""
        response = self.client.get(reverse('opencourt:teams'))
        self.assertTemplateUsed(response, 'opencourt/teams.html')

    def test_empty_database(self):
        """Teams page should render with an empty team list when no teams exist."""
        response = self.client.get(reverse('opencourt:teams'))
        self.assertEqual(response.status_code, 200)
        self.assertEqual(len(response.context['team_list']), 0)

    def test_teams_in_context(self):
        """All created teams should appear in the team_list context variable."""
        conf = _make_conference()
        _make_team(conference=conf, source_id=1, school='Duke', mascot='BD', slug='duke')
        _make_team(conference=conf, source_id=2, school='UNC', mascot='TH', slug='unc')

        response = self.client.get(reverse('opencourt:teams'))
        self.assertEqual(len(response.context['team_list']), 2)

    def test_teams_ordered_alphabetically(self):
        """Teams should be ordered by school name (A-Z)."""
        conf = _make_conference()
        _make_team(conference=conf, source_id=1, school='Zion', mascot='Z', slug='zion')
        _make_team(conference=conf, source_id=2, school='Alabama', mascot='A', slug='alabama')

        response = self.client.get(reverse('opencourt:teams'))
        schools = [t.school for t in response.context['team_list']]
        self.assertEqual(schools, ['Alabama', 'Zion'])

    def test_conference_list_in_context(self):
        """Context should include conference_list for the filter dropdown."""
        _make_conference()
        response = self.client.get(reverse('opencourt:teams'))
        self.assertIn('conference_list', response.context)
        self.assertEqual(len(response.context['conference_list']), 1)

# =============================================================================
# ConferenceListView Tests
# =============================================================================

@OVERRIDE_STORAGES
class ConferenceListViewTest(TestCase):
    """
    Tests for ConferenceListView (GET /conferences/).

    Two-panel layout: sidebar of conferences, right panel with teams
    and aggregate stats (team_count, avg_win_pct, total_wins, total_losses).
    """

    def test_status_200(self):
        """Conferences page should return HTTP 200."""
        response = self.client.get(reverse('opencourt:conferences'))
        self.assertEqual(response.status_code, 200)

    def test_correct_template(self):
        """Conferences page should use opencourt/conferences.html."""
        response = self.client.get(reverse('opencourt:conferences'))
        self.assertTemplateUsed(response, 'opencourt/conferences.html')

    def test_empty_database(self):
        """Page should render when no conferences exist."""
        response = self.client.get(reverse('opencourt:conferences'))
        self.assertEqual(response.status_code, 200)

    def test_conference_annotations(self):
        """
        Each conference in the queryset should be annotated with team_count.
        Verify the annotation is present and correct.
        """
        conf = _make_conference()
        _make_team(conference=conf, source_id=1, school='T1', mascot='M1', slug='t1')
        _make_team(conference=conf, source_id=2, school='T2', mascot='M2', slug='t2')

        response = self.client.get(reverse('opencourt:conferences'))
        conf_obj = response.context['conference_list'][0]
        self.assertEqual(conf_obj.team_count, 2)

# =============================================================================
# RankingsListView Tests
# =============================================================================

@OVERRIDE_STORAGES
class RankingsListViewTest(TestCase):
    """
    Tests for RankingsListView (GET /rankings/).

    Displays AP Top 25 and Coaches Poll side by side with week
    navigation via the ?week=N query parameter.
    """

    def setUp(self):
        """Create teams and rankings for testing week navigation."""
        self.conf = _make_conference()
        self.team = _make_team(conference=self.conf)
        _make_season_stats(self.team)

    def test_status_200(self):
        """Rankings page should return HTTP 200."""
        response = self.client.get(reverse('opencourt:rankings'))
        self.assertEqual(response.status_code, 200)

    def test_correct_template(self):
        """Rankings page should use opencourt/rankings.html."""
        response = self.client.get(reverse('opencourt:rankings'))
        self.assertTemplateUsed(response, 'opencourt/rankings.html')

    def test_empty_database(self):
        """Page should render when no rankings exist (preseason / early season)."""
        response = self.client.get(reverse('opencourt:rankings'))
        self.assertEqual(response.status_code, 200)

    def test_week_param_selects_correct_week(self):
        """
        Passing ?week=5 should set selected_week to 5 in context.
        """
        _make_ranking(self.team, week=5, poll_type='AP Top 25')
        response = self.client.get(reverse('opencourt:rankings') + '?week=5')
        self.assertEqual(response.context['selected_week'], 5)

    def test_invalid_week_param_falls_back(self):
        """
        Passing ?week=abc (non-integer) should fall back to the most
        recent week rather than crashing.
        """
        _make_ranking(self.team, week=10, poll_type='AP Top 25')
        response = self.client.get(reverse('opencourt:rankings') + '?week=abc')
        self.assertEqual(response.status_code, 200)
        # Should fall back to most recent week (10)
        self.assertEqual(response.context['selected_week'], 10)

    def test_available_weeks_in_context(self):
        """
        Context should include available_weeks list for the week dropdown,
        ordered newest-first.
        """
        _make_ranking(self.team, week=5, poll_type='AP Top 25')
        _make_ranking(self.team, week=10, poll_type='AP Top 25',
                      poll_date=timezone.now() + timedelta(weeks=5))

        response = self.client.get(reverse('opencourt:rankings'))
        weeks = [w['week'] for w in response.context['available_weeks']]
        self.assertEqual(weeks, [10, 5])

    def test_conference_list_in_context(self):
        """Context should include conference_list for the filter dropdown."""
        response = self.client.get(reverse('opencourt:rankings'))
        self.assertIn('conference_list', response.context)

# =============================================================================
# TeamDetailView Tests
# =============================================================================

@OVERRIDE_STORAGES
class TeamDetailViewTest(TestCase):
    """
    Tests for TeamDetailView (GET /<slug>/).

    The team detail page shows historical stats as ApexCharts, a current
    season schedule with expandable box scores, and team metadata.
    """

    def setUp(self):
        """Create a team with season stats and a game for testing."""
        self.conf = _make_conference()
        self.team = _make_team(conference=self.conf, slug='duke-blue-devils')
        self.stats = _make_season_stats(self.team)

    def test_status_200(self):
        """Team detail page should return HTTP 200 for a valid slug."""
        response = self.client.get(
            reverse('opencourt:team-detail', kwargs={'slug': 'duke-blue-devils'})
        )
        self.assertEqual(response.status_code, 200)

    def test_correct_template(self):
        """Team detail should use opencourt/team_details.html."""
        response = self.client.get(
            reverse('opencourt:team-detail', kwargs={'slug': 'duke-blue-devils'})
        )
        self.assertTemplateUsed(response, 'opencourt/team_details.html')

    def test_invalid_slug_returns_404(self):
        """A non-existent slug should return HTTP 404."""
        response = self.client.get(
            reverse('opencourt:team-detail', kwargs={'slug': 'nonexistent-team'})
        )
        self.assertEqual(response.status_code, 404)

    def test_team_in_context(self):
        """Context should contain the correct team object."""
        response = self.client.get(
            reverse('opencourt:team-detail', kwargs={'slug': 'duke-blue-devils'})
        )
        self.assertEqual(response.context['team'].pk, self.team.pk)

    def test_chart_data_is_valid_json(self):
        """
        Chart data context variables (stat_years, wins, losses, etc.) should
        be valid JSON strings that JavaScript can parse.
        """
        response = self.client.get(
            reverse('opencourt:team-detail', kwargs={'slug': 'duke-blue-devils'})
        )
        # These should be valid JSON arrays
        for key in ['stat_years', 'wins', 'losses', 'win_pct', 'off_rtg', 'opp_rtg']:
            try:
                parsed = json.loads(response.context[key])
                self.assertIsInstance(parsed, list)
            except (json.JSONDecodeError, KeyError) as e:
                self.fail(f"Context key '{key}' is not valid JSON: {e}")

    def test_team_with_no_stats(self):
        """
        A team with no season stats should still render — chart arrays
        should be empty JSON lists.
        """
        empty_team = _make_team(
            source_id=999, school='NewTeam', mascot='Mascot', slug='new-team'
        )
        response = self.client.get(
            reverse('opencourt:team-detail', kwargs={'slug': 'new-team'})
        )
        self.assertEqual(response.status_code, 200)
        self.assertEqual(json.loads(response.context['wins']), [])

    def test_schedule_in_context(self):
        """
        Context should include a 'schedule' list. Each entry has 'game',
        'is_home', 'opponent', 'team_points', 'opp_points', 'won'.
        """
        opp = _make_team(source_id=2, school='UNC', mascot='TH', slug='unc')
        _make_game(
            self.team, opp,
            season=date.today().year,
            start_date=timezone.now(),
        )

        response = self.client.get(
            reverse('opencourt:team-detail', kwargs={'slug': 'duke-blue-devils'})
        )
        schedule = response.context['schedule']
        self.assertEqual(len(schedule), 1)
        self.assertTrue(schedule[0]['is_home'])
        self.assertEqual(schedule[0]['opponent'].pk, opp.pk)
        self.assertEqual(schedule[0]['team_points'], 78)
        self.assertEqual(schedule[0]['opp_points'], 72)

# =============================================================================
# UpcomingView Tests
# =============================================================================

@OVERRIDE_STORAGES
class UpcomingViewTest(TestCase):
    """
    Tests for UpcomingView (GET /upcoming/).

    Supports two modes:
      ?mode=upcoming — future scheduled games with predictions
      ?mode=results  — completed games with prediction accuracy

    Predictions require the ML model file, which doesn't exist in test.
    We mock make_predictions to avoid FileNotFoundError.
    """

    def setUp(self):
        """Create teams with stats and games for both modes."""
        self.conf = _make_conference()
        self.home = _make_team(
            conference=self.conf, source_id=1, school='Duke',
            mascot='BD', slug='duke'
        )
        self.away = _make_team(
            conference=self.conf, source_id=2, school='UNC',
            mascot='TH', slug='unc'
        )
        current_year = date.today().year
        _make_season_stats(self.home, season=current_year)
        _make_season_stats(self.away, season=current_year)

    def test_status_200_upcoming_mode(self):
        """Upcoming page should return HTTP 200 in default (upcoming) mode."""
        response = self.client.get(reverse('opencourt:upcoming'))
        self.assertEqual(response.status_code, 200)

    def test_correct_template(self):
        """Upcoming page should use opencourt/head_head.html."""
        response = self.client.get(reverse('opencourt:upcoming'))
        self.assertTemplateUsed(response, 'opencourt/head_head.html')

    def test_default_mode_is_upcoming(self):
        """Without ?mode= param, the view should default to 'upcoming'."""
        response = self.client.get(reverse('opencourt:upcoming'))
        self.assertEqual(response.context['mode'], 'upcoming')

    def test_results_mode(self):
        """?mode=results should set mode to 'results' in context."""
        response = self.client.get(reverse('opencourt:upcoming') + '?mode=results')
        self.assertEqual(response.context['mode'], 'results')

    def test_invalid_mode_falls_back_to_upcoming(self):
        """?mode=invalid should fall back to 'upcoming'."""
        response = self.client.get(reverse('opencourt:upcoming') + '?mode=garbage')
        self.assertEqual(response.context['mode'], 'upcoming')

    @patch('opencourt.views.predict_game')
    def test_upcoming_shows_future_games(self, mock_predict):
        """
        In upcoming mode, scheduled games in the future should appear
        in the context. Mock predictions to avoid model file dependency.
        """
        import numpy as np
        mock_predict.return_value = np.array([1])

        tomorrow = timezone.now() + timedelta(days=1)
        _make_game(
            self.home, self.away,
            source_id='future-1',
            status='scheduled',
            start_date=tomorrow,
            home_points=None,
            away_points=None,
            home_winner=None,
            away_winner=None,
        )

        response = self.client.get(
            reverse('opencourt:upcoming') + '?mode=upcoming&date=all'
        )
        self.assertEqual(response.status_code, 200)
        # The game should appear in either games or all_games
        total_games = len(response.context['games']) + len(response.context['all_games'])
        self.assertGreaterEqual(total_games, 1)

    @patch('opencourt.views.predict_game')
    def test_results_mode_shows_completed_games(self, mock_predict):
        """
        In results mode, completed games should appear in context
        with prediction accuracy summary.
        """
        import numpy as np
        mock_predict.return_value = np.array([1])

        _make_game(
            self.home, self.away,
            source_id='completed-1',
            status='final',
            start_date=timezone.now(),
            home_winner=True,
            away_winner=False,
        )

        response = self.client.get(
            reverse('opencourt:upcoming') + '?mode=results&date=all'
        )
        self.assertEqual(response.status_code, 200)
        self.assertIn('accuracy', response.context)

    def test_date_param_invalid_falls_back(self):
        """?date=not-a-date should fall back to today without crashing."""
        response = self.client.get(
            reverse('opencourt:upcoming') + '?date=not-a-date'
        )
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.context['selected_date'], date.today())

    def test_show_all_flag(self):
        """?date=all should set show_all=True and selected_date=None."""
        response = self.client.get(
            reverse('opencourt:upcoming') + '?date=all'
        )
        self.assertEqual(response.status_code, 200)
        self.assertTrue(response.context['show_all'])
        self.assertIsNone(response.context['selected_date'])

    def test_upcoming_dates_in_context(self):
        """
        Context should include upcoming_dates — a list of 7 date objects
        for the date tab navigation.
        """
        response = self.client.get(reverse('opencourt:upcoming'))
        self.assertEqual(len(response.context['upcoming_dates']), 7)
