# apps.py — App config for the Tailwind theme app.
#
# Do not edit this file — Django uses it to register the app automatically.
#
# What to edit (and what not to):
#   EDIT   → theme/static_src/src/styles.css   (Tailwind entry point — add @source
#                                                 directives, change DaisyUI theme, etc.)
#   EDIT   → theme/static_src/package.json      (add/remove npm packages if needed)
#   NEVER  → theme/static/css/dist/styles.css   (auto-generated, overwritten on every build)
#   NEVER  → this file (apps.py)
#
# Commands:
#   python manage.py tailwind install  — install npm packages (one-time after cloning)
#   python manage.py tailwind start    — watch for changes and recompile CSS (dev)
#   python manage.py tailwind build    — compile and minify CSS (production)

from django.apps import AppConfig


class ThemeConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'theme'
